package appfunctions_aggregated_deps

import androidx.appfunctions.AppFunctionComponentRegistry
import javax.`annotation`.processing.Generated

@AppFunctionComponentRegistry(
  componentCategory = "INVENTORY",
  componentNames = [
    "com.testdata.diff.${'$'}SimpleFunction_AppFunctionInventory",
  ],
)
@Generated("androidx.appfunctions.compiler.AppFunctionCompiler")
public class `$ComTestdataDiff_InventoryComponentRegistry`
