package appfunctions_aggregated_deps

import androidx.appfunctions.AppFunctionComponentRegistry
import javax.`annotation`.processing.Generated

@AppFunctionComponentRegistry(
  componentCategory = "INVOKER",
  componentNames = [
    "com.testdata.diff.${'$'}SimpleFunction_AppFunctionInvoker",
  ],
)
@Generated("androidx.appfunctions.compiler.AppFunctionCompiler")
public class `$ComTestdataDiff_InvokerComponentRegistry`
