package com.testdata

import androidx.appfunctions.`internal`.AppFunctionInventory
import androidx.appfunctions.metadata.AppFunctionArrayTypeMetadata
import androidx.appfunctions.metadata.AppFunctionMetadata
import androidx.appfunctions.metadata.AppFunctionParameterMetadata
import androidx.appfunctions.metadata.AppFunctionPrimitiveTypeMetadata
import androidx.appfunctions.metadata.AppFunctionSchemaMetadata
import javax.`annotation`.processing.Generated
import kotlin.String
import kotlin.collections.List
import kotlin.collections.Map

/**
 * Source Files:
 * FakeAllPrimitiveParamsImpl.....kt
 * FakeSchemas.....kt
 */
@Generated("androidx.appfunctions.compiler.AppFunctionCompiler")
public class `$FakeAllPrimitiveParamsImpl_AppFunctionInventory` : AppFunctionInventory {
  override val functionIdToMetadataMap: Map<String, AppFunctionMetadata> = mapOf()

  private val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = AppFunctionSchemaMetadata(category= "fake_schema_category",
      name="allPrimitiveParams", version=1)

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_PARAMETER_METADATA_ARG1_PRIMITIVE_DATA_TYPE:
      AppFunctionPrimitiveTypeMetadata = AppFunctionPrimitiveTypeMetadata(
          type = 7,
          isNullable = false
      )

  private val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_ARG1_PARAMETER_METADATA:
      AppFunctionParameterMetadata = AppFunctionParameterMetadata(
          name = "arg1",
          isRequired = true,
          dataType =
          COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_PARAMETER_METADATA_ARG1_PRIMITIVE_DATA_TYPE
      )

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_PARAMETER_METADATA_ARG2_PRIMITIVE_DATA_TYPE:
      AppFunctionPrimitiveTypeMetadata = AppFunctionPrimitiveTypeMetadata(
          type = 6,
          isNullable = false
      )

  private val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_ARG2_PARAMETER_METADATA:
      AppFunctionParameterMetadata = AppFunctionParameterMetadata(
          name = "arg2",
          isRequired = true,
          dataType =
          COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_PARAMETER_METADATA_ARG2_PRIMITIVE_DATA_TYPE
      )

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_PARAMETER_METADATA_ARG3_PRIMITIVE_DATA_TYPE:
      AppFunctionPrimitiveTypeMetadata = AppFunctionPrimitiveTypeMetadata(
          type = 5,
          isNullable = false
      )

  private val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_ARG3_PARAMETER_METADATA:
      AppFunctionParameterMetadata = AppFunctionParameterMetadata(
          name = "arg3",
          isRequired = true,
          dataType =
          COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_PARAMETER_METADATA_ARG3_PRIMITIVE_DATA_TYPE
      )

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_PARAMETER_METADATA_ARG4_PRIMITIVE_DATA_TYPE:
      AppFunctionPrimitiveTypeMetadata = AppFunctionPrimitiveTypeMetadata(
          type = 4,
          isNullable = false
      )

  private val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_ARG4_PARAMETER_METADATA:
      AppFunctionParameterMetadata = AppFunctionParameterMetadata(
          name = "arg4",
          isRequired = true,
          dataType =
          COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_PARAMETER_METADATA_ARG4_PRIMITIVE_DATA_TYPE
      )

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_PARAMETER_METADATA_ARG5_PRIMITIVE_DATA_TYPE:
      AppFunctionPrimitiveTypeMetadata = AppFunctionPrimitiveTypeMetadata(
          type = 8,
          isNullable = false
      )

  private val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_ARG5_PARAMETER_METADATA:
      AppFunctionParameterMetadata = AppFunctionParameterMetadata(
          name = "arg5",
          isRequired = true,
          dataType =
          COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_PARAMETER_METADATA_ARG5_PRIMITIVE_DATA_TYPE
      )

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_PARAMETER_METADATA_ARG6_PRIMITIVE_DATA_TYPE:
      AppFunctionPrimitiveTypeMetadata = AppFunctionPrimitiveTypeMetadata(
          type = 1,
          isNullable = false
      )

  private val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_ARG6_PARAMETER_METADATA:
      AppFunctionParameterMetadata = AppFunctionParameterMetadata(
          name = "arg6",
          isRequired = true,
          dataType =
          COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_PARAMETER_METADATA_ARG6_PRIMITIVE_DATA_TYPE
      )

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_PARAMETER_METADATA_ARG7_PRIMITIVE_DATA_TYPE:
      AppFunctionPrimitiveTypeMetadata = AppFunctionPrimitiveTypeMetadata(
          type = 2,
          isNullable = false
      )

  private val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_ARG7_PARAMETER_METADATA:
      AppFunctionParameterMetadata = AppFunctionParameterMetadata(
          name = "arg7",
          isRequired = true,
          dataType =
          COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_PARAMETER_METADATA_ARG7_PRIMITIVE_DATA_TYPE
      )

  private val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_PARAMETER_METADATA_LIST:
      List<AppFunctionParameterMetadata> = buildList{
    add(
      COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_ARG1_PARAMETER_METADATA
    )
    add(
      COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_ARG2_PARAMETER_METADATA
    )
    add(
      COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_ARG3_PARAMETER_METADATA
    )
    add(
      COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_ARG4_PARAMETER_METADATA
    )
    add(
      COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_ARG5_PARAMETER_METADATA
    )
    add(
      COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_ARG6_PARAMETER_METADATA
    )
    add(
      COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEPARAMS_ARG7_PARAMETER_METADATA
    )
  }

  private val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_SCHEMA_METADATA:
      AppFunctionSchemaMetadata? = AppFunctionSchemaMetadata(category= "fake_schema_category",
      name="allPrimitiveParams", version=1)

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG1_ARRAY_DATA_TYPE_PRIMITIVE_ITEM_TYPE:
      AppFunctionPrimitiveTypeMetadata = AppFunctionPrimitiveTypeMetadata(
          type = 7,
          isNullable = false
      )

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG1_ARRAY_DATA_TYPE:
      AppFunctionArrayTypeMetadata = AppFunctionArrayTypeMetadata(
          itemType =
          COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG1_ARRAY_DATA_TYPE_PRIMITIVE_ITEM_TYPE,
          isNullable = false
      )

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_ARG1_PARAMETER_METADATA:
      AppFunctionParameterMetadata = AppFunctionParameterMetadata(
          name = "arg1",
          isRequired = true,
          dataType =
          COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG1_ARRAY_DATA_TYPE
      )

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG2_ARRAY_DATA_TYPE_PRIMITIVE_ITEM_TYPE:
      AppFunctionPrimitiveTypeMetadata = AppFunctionPrimitiveTypeMetadata(
          type = 6,
          isNullable = false
      )

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG2_ARRAY_DATA_TYPE:
      AppFunctionArrayTypeMetadata = AppFunctionArrayTypeMetadata(
          itemType =
          COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG2_ARRAY_DATA_TYPE_PRIMITIVE_ITEM_TYPE,
          isNullable = false
      )

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_ARG2_PARAMETER_METADATA:
      AppFunctionParameterMetadata = AppFunctionParameterMetadata(
          name = "arg2",
          isRequired = true,
          dataType =
          COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG2_ARRAY_DATA_TYPE
      )

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG3_ARRAY_DATA_TYPE_PRIMITIVE_ITEM_TYPE:
      AppFunctionPrimitiveTypeMetadata = AppFunctionPrimitiveTypeMetadata(
          type = 5,
          isNullable = false
      )

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG3_ARRAY_DATA_TYPE:
      AppFunctionArrayTypeMetadata = AppFunctionArrayTypeMetadata(
          itemType =
          COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG3_ARRAY_DATA_TYPE_PRIMITIVE_ITEM_TYPE,
          isNullable = false
      )

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_ARG3_PARAMETER_METADATA:
      AppFunctionParameterMetadata = AppFunctionParameterMetadata(
          name = "arg3",
          isRequired = true,
          dataType =
          COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG3_ARRAY_DATA_TYPE
      )

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG4_ARRAY_DATA_TYPE_PRIMITIVE_ITEM_TYPE:
      AppFunctionPrimitiveTypeMetadata = AppFunctionPrimitiveTypeMetadata(
          type = 4,
          isNullable = false
      )

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG4_ARRAY_DATA_TYPE:
      AppFunctionArrayTypeMetadata = AppFunctionArrayTypeMetadata(
          itemType =
          COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG4_ARRAY_DATA_TYPE_PRIMITIVE_ITEM_TYPE,
          isNullable = false
      )

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_ARG4_PARAMETER_METADATA:
      AppFunctionParameterMetadata = AppFunctionParameterMetadata(
          name = "arg4",
          isRequired = true,
          dataType =
          COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG4_ARRAY_DATA_TYPE
      )

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG5_ARRAY_DATA_TYPE_PRIMITIVE_ITEM_TYPE:
      AppFunctionPrimitiveTypeMetadata = AppFunctionPrimitiveTypeMetadata(
          type = 8,
          isNullable = false
      )

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG5_ARRAY_DATA_TYPE:
      AppFunctionArrayTypeMetadata = AppFunctionArrayTypeMetadata(
          itemType =
          COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG5_ARRAY_DATA_TYPE_PRIMITIVE_ITEM_TYPE,
          isNullable = false
      )

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_ARG5_PARAMETER_METADATA:
      AppFunctionParameterMetadata = AppFunctionParameterMetadata(
          name = "arg5",
          isRequired = true,
          dataType =
          COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG5_ARRAY_DATA_TYPE
      )

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG6_ARRAY_DATA_TYPE_PRIMITIVE_ITEM_TYPE:
      AppFunctionPrimitiveTypeMetadata = AppFunctionPrimitiveTypeMetadata(
          type = 1,
          isNullable = false
      )

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG6_ARRAY_DATA_TYPE:
      AppFunctionArrayTypeMetadata = AppFunctionArrayTypeMetadata(
          itemType =
          COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG6_ARRAY_DATA_TYPE_PRIMITIVE_ITEM_TYPE,
          isNullable = false
      )

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_ARG6_PARAMETER_METADATA:
      AppFunctionParameterMetadata = AppFunctionParameterMetadata(
          name = "arg6",
          isRequired = true,
          dataType =
          COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG6_ARRAY_DATA_TYPE
      )

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG7_ARRAY_DATA_TYPE_PRIMITIVE_ITEM_TYPE:
      AppFunctionPrimitiveTypeMetadata = AppFunctionPrimitiveTypeMetadata(
          type = 2,
          isNullable = false
      )

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG7_ARRAY_DATA_TYPE:
      AppFunctionArrayTypeMetadata = AppFunctionArrayTypeMetadata(
          itemType =
          COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG7_ARRAY_DATA_TYPE_PRIMITIVE_ITEM_TYPE,
          isNullable = false
      )

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_ARG7_PARAMETER_METADATA:
      AppFunctionParameterMetadata = AppFunctionParameterMetadata(
          name = "arg7",
          isRequired = true,
          dataType =
          COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_ARG7_ARRAY_DATA_TYPE
      )

  private
      val COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_PARAMETER_METADATA_LIST:
      List<AppFunctionParameterMetadata> = buildList{
    add(
      COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_ARG1_PARAMETER_METADATA
    )
    add(
      COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_ARG2_PARAMETER_METADATA
    )
    add(
      COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_ARG3_PARAMETER_METADATA
    )
    add(
      COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_ARG4_PARAMETER_METADATA
    )
    add(
      COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_ARG5_PARAMETER_METADATA
    )
    add(
      COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_ARG6_PARAMETER_METADATA
    )
    add(
      COM_TESTDATA_FAKEALLPRIMITIVEPARAMSIMPL_ALLPRIMITIVEARRAYPARAMS_ARG7_PARAMETER_METADATA
    )
  }
}
